CLI = ./bin/uhppote-cli --config '.UTO311-L04'
DEBUG = --debug
CARD = 6154412
SERIALNO = 423187757
DOOR = 3
DATETIME = `date "+%Y-%m-%d %H:%M:%S"`

get-devices: 
	$(CLI) $(DEBUG) get-devices
 
set-address: 
	$(CLI) $(DEBUG) set-address $(SERIALNO) '192.168.1.125' '255.255.255.0' '0.0.0.0'

get-status:  
	$(CLI) $(DEBUG) get-status $(SERIALNO)
 
get-time:  
	$(CLI) $(DEBUG) get-time $(SERIALNO)

set-time:  
	$(CLI) $(DEBUG) set-time $(SERIALNO)
	$(CLI) $(DEBUG) set-time $(SERIALNO) "$(DATETIME)"

get-door-delay:  
	$(CLI) $(DEBUG) get-door-delay $(SERIALNO) $(DOOR)

set-door-delay:  
	$(CLI) $(DEBUG) set-door-delay $(SERIALNO) $(DOOR) 5

get-door-control: 
	$(CLI) $(DEBUG) get-door-control $(SERIALNO) $(DOOR)

set-door-control: 
	$(CLI) $(DEBUG) set-door-control $(SERIALNO) $(DOOR) 'normally closed'

get-listener:  
	$(CLI) $(DEBUG) get-listener $(SERIALNO)

set-listener:  
	$(CLI) $(DEBUG) set-listener $(SERIALNO) 192.168.1.100:40000
 
get-cards:  
	$(CLI) $(DEBUG) get-cards $(SERIALNO)
 
get-card:  
	$(CLI) $(DEBUG) get-card $(SERIALNO) $(CARD)
 
grant:  
	$(CLI) $(DEBUG) grant $(SERIALNO) $(CARD) 2019-01-01 2019-12-31 1

revoke:  
	$(CLI) $(DEBUG) revoke $(SERIALNO) $(CARD)

revoke-all:  
	$(CLI) $(DEBUG) revoke-all $(SERIALNO)
 
load-acl:  
	$(CLI) $(DEBUG) load-acl UTO311-L04.tsv
 
get-events:  
	$(CLI) $(DEBUG) get-events $(SERIALNO)

get-event-index:  
	$(CLI) $(DEBUG) get-event-index $(SERIALNO)

set-event-index:  
	$(CLI) $(DEBUG) set-event-index $(SERIALNO) 23

open:  
	$(CLI) $(DEBUG) open $(SERIALNO) 1

listen:  
	$(CLI) $(DEBUG) --bind 192.168.1.100:40000 $(DEBUG) listen 
