FROM ubuntu

EXPOSE 8080

RUN mkdir -p /etc/uhppoted
ADD ./docker/uhppoted.conf /etc/uhppoted/
ADD ./docker/ca.cert       /etc/uhppoted/rest/
ADD ./docker/uhppoted.cert /etc/uhppoted/rest/
ADD ./docker/uhppoted.key  /etc/uhppoted/rest/

RUN mkdir -p /var/uhppoted

WORKDIR /opt/uhppoted 
ADD ./docker/linux/uhppoted-rest     .
ADD ./docker/linux/uhppote-simulator .

ENTRYPOINT /opt/uhppoted/uhppoted-rest
